### ISSUE TITLE
Replace + with ... hint doesn't appear in return statement

### ISSUE THREAD

**Issue by INeedMySpace** [markiewb/nb-additional-hints#67] opened 2016-02-18 12:49 UTC
Hi, I tried it in freshly created toString() method for my class which has 
`return "Foo{" + "bar=" + bar + '}';`
and there is no such option in Alt-Enter hints.
But if I change it to
```
String result = "Foo{" + "bar=" + bar + '}';
return result;
```
where will be such option.
Netbeans 8.0.2, 8.1

**Comment by markiewb** [comment] 2016-02-20 12:27
Duplicate of https://github.com/markiewb/nb-additional-hints/issues/54 . Closing. When I have time, i will release version 1.6.0, which includes this fix. 

In the meantime you can try the snapshot https://github.com/markiewb/nb-additional-hints/releases/tag/v1.6.0.3 and give me feedback.

**Closed by markiewb** 2016-02-20 12:27 UTC
Labels: duplicate
