### ISSUE TITLE
False positive on dead instanceof hint

### ISSUE THREAD

**Issue by RayDeCampo** [markiewb/nb-additional-hints#52] opened 2015-03-13 14:40 UTC
I am getting a false positive on the dead instanceof hint for the following code:

        for (final Object t : timerService.getTimers())
        {
            // If the timers aren't Timers, skip
            if (!(t instanceof Timer))
            {
                continue;
            }
            final Timer candidate = (Timer)t;

(Here timerService is a javax.ejb.TimerService and Timer is javax.ejb.Timer.)

**Comment by markiewb** [comment] 2015-03-13 15:39
Thank you for the report. It is a duplicate of #50. It will be fixed in the next version.

In the meantime disable the hint or try the new snapshot https://github.com/markiewb/nb-additional-hints/releases/tag/v1.4.1.1

**Closed by markiewb** 2015-03-13 15:39 UTC
Labels: bug

**Comment by RayDeCampo** [comment] 2015-03-13 16:25
Thanks, sorry about the dupe

**Comment by markiewb** [comment] 2015-03-13 16:30
@RayDeCampo: No problem. Giving feedback is better than giving no feedback
