### ISSUE TITLE
Replace + with... doesn't always appear

### ISSUE THREAD

**Issue by MarkJeronimus** [markiewb/nb-additional-hints#46] opened 2015-03-06 08:46 UTC
In this code:

    String variable = name + " (" + position.getX() + ", " + position.getY() + ')';
    return "Found " + variable + " entries";

Pressing Alt+Enter on the second line works, I see the three replacement options. Pressing it on the first line does nothing (brings up NB's standard actions).

When I replace the char literals with string literals, it works! I make it a StringBuilder and then I can then replace the literals with chars again because there is an overloaded method `StringBuilder.append(char c)`

**Comment by markiewb** [comment] 2015-03-07 09:58
>  Pressing it on the first line does nothing (brings up NB's standard actions).
Place the cursor at the right side of the assignment.
```String variable = na<CARET>me + " (" + position.getX() + ", " + position.getY() + ')';```

The issue with the chars is known as https://github.com/markiewb/nb-additional-hints/issues/2 Thank you for your example.
```
//		String v1 = name + " (" + x + ", " + y + ')';
		String v1 = MessageFormat.format("{0} ({1}, {2}{3}", name, x, y, ')');
//		String v2 = name + " (" + x + ", " + y + ')';
		String v2 = String.format("%s (%s, %s%s", name, x, y, ')');
//		String v3 = name + " (" + x + ", " + y + ')';
		String v3 = new StringBuilder().append(name).append(" (").append(x).append(", ").append(y).append(')').toString();
```

**Comment by markiewb** [comment] 2015-03-07 19:23
Closing as duplicate of #2

**Closed by markiewb** 2015-03-07 19:23 UTC
Labels: duplicate, question
